# Generated by Django 4.2.11 on 2024-12-26 05:22

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('request_time', models.DateTimeField(default=myapp.models.get_local_time)),
                ('flag', models.IntegerField(default=0)),
            ],
        ),
    ]
