# Generated by Django 4.2.11 on 2024-12-26 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_videoconsultationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmeet_url', models.URLField()),
                ('username', models.CharField(max_length=100)),
                ('request_time', models.DateTimeField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.videoconsultationrequest')),
            ],
        ),
    ]
