# Generated by Django 4.2.11 on 2024-12-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensordata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('temperature', models.CharField(max_length=255)),
                ('spo2', models.CharField(max_length=255)),
                ('heart_rate', models.CharField(max_length=255)),
                ('systolic_pressure', models.CharField(max_length=255)),
                ('diastolic_pressure', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
